name: Lint python
run-name: Linting python files on ${{ github.repository }}

on:
  workflow_call:

jobs:
  py-lint:
    name: Perform lint python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0c6ab70129fa3660acd9cd2b51e8685d619cd613 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3.5.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install and upgrade PIP
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: >
          pip install
          ruff
          black
          mypy

      - name: Ruff Linter
        run: ruff check . --diff

      - name: Black Formatter
        run: black . --diff --check

      - name: Mypy Type Checker
        run: >
          mypy .
          --install-types
          --non-interactive
